spring:
  cloud:
    gateway:
      routes:
        - id: ticket-service-user-service
          uri: lb://ticket-service-user${unique-name:}-service/api/user-service/**
          predicates:
            - Path=/api/user-service/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/user-service/passenger
                  - /api/user-service/query
                  - /api/user-service/logout
                  - /api/user-service/deletion

        - id: ticket-service-ticket-service
          uri: lb://ticket-service-ticket${unique-name:}-service/api/ticket-service/**
          predicates:
            - Path=/api/ticket-service/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/ticket-service/ticket/purchase
                  - /api/ticket-service/ticket/pay/query
                  - /api/ticket-service/ticket/cancel

        - id: ticket-service-pay-service
          uri: lb://ticket-service-pay${unique-name:}-service/api/pay-service/**
          predicates:
            - Path=/api/pay-service/**

        - id: ticket-service-order-service
          uri: lb://ticket-service-order${unique-name:}-service/api/order-service/**
          predicates:
            - Path=/api/order-service/**
          filters:
            - name: TokenValidate
              args:
                blackPathPre:
                  - /api/order-service/order/ticket/query
                  - /api/order-service/order/ticket/page
                  - /api/order-service/order/ticket/self/page
